import { Cinzel, Montserrat } from "next/font/google";
import Footer from "./Footer";
import "./globals.css";

const cinzel = Cinzel({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-cinzel",
});

const monteserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${monteserrat.variable} ${cinzel.variable}`}>
      <body className="flex min-h-screen flex-col font-sans">
        {children}
        <Footer />
      </body>
    </html>
  );
}
